### ISSUE TITLE
IW6 PS4 Incompatible

### ISSUE THREAD

**Issue by DeathRGH** [JariKCoding/CoDLuaDecompiler#8]
Scripts dumped from the **ps4** version of **ghosts** seem to be detected as **T6 instead of IW6**.
I can provide dumps if needed.

```CoD Lua Decompiler
Total of 1 to process.
System.NotImplementedException: The method or operation is not implemented.
   at CoDLuaDecompiler.Decompiler.LuaFile.Structures.LuaConstant.Havok.HavokLuaConstant.Parse()
   at CoDLuaDecompiler.Decompiler.LuaFile.Structures.LuaFunction.Havok.HavokLuaFunctionT6.ReadConstants()
   at CoDLuaDecompiler.Decompiler.LuaFile.Structures.LuaFunction.Havok.HavokLuaFunction.Parse()
   at CoDLuaDecompiler.Decompiler.LuaFile.Structures.LuaFunction.LuaFunction..ctor(ILuaFile luaFile, BinaryReader reader)
   at CoDLuaDecompiler.Decompiler.LuaFile.Havok.HavokLuaFileT6.ReadFunctions()
   at CoDLuaDecompiler.Decompiler.LuaFile.LuaFile.Parse()
   at CoDLuaDecompiler.Decompiler.LuaFile.LuaFileFactory.Create(BinaryReader reader, String filePath, Boolean useDebugInfo)
   at CoDLuaDecompiler.Decompiler.LuaFile.LuaFileFactory.Create(String filePath, Boolean usesDebugInfo)
   at CoDLuaDecompiler.CLI.Program.HandleFile(String filePath)
Press enter to exit

**Comment by realityuk** [comment]
Try removing support for T6 maybe
